### ISSUE TITLE
进度条

### ISSUE THREAD

**Issue by cydia885** [1014156094/vue-audio-player#10]
你好，我想问下这个进度条拖动要怎么引入那个touchemulator脚本？

**Comment by 1206993746** [comment]
有详细的使用教程吗

**Comment by 1014156094** [comment]
> 有详细的使用教程吗
我编辑了，我觉得不难理解了，你看看还有什么问题。

**Comment by 1014156094** [comment]
> 有详细的使用教程吗

我编辑了，我觉得不难理解了，你看看还有什么问题
