### ISSUE TITLE
组件所在的页面关闭时后台一直报错 Cannot read property 'currentTime' of undefined     at VueComponent.playing。 组件杀死定时器并没有清除

### ISSUE THREAD

**Issue by darkmercy** [1014156094/vue-audio-player#12]
你好，请使用下面的链接创建 issue 以帮助我们更快的排查问题。

https://codesandbox.io/s/liripengvue-audio-player-issue-moban-cb57s?fontsize=14

---

Please use the link below to create a new issue.

https://codesandbox.io/s/liripengvue-audio-player-issue-moban-cb57s?fontsize=14

**Comment by 1014156094** [comment]
v1.0.7 版本已修复
