### ISSUE TITLE
能给进度条加个过渡效果吗

### ISSUE THREAD

**Issue by zengzhe1996** [1014156094/vue-audio-player#16]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by zengzhe1996** [comment]
能给进度条加个过渡效果吗 感觉这样会更好点

**Comment by 1014156094** [comment]
没懂意思，要什么时候过渡，怎么过渡

**Comment by 1014156094** [comment]
人捏~
