### ISSUE TITLE
格式化日期 没有显示小时

### ISSUE THREAD

**Issue by KingLiLi** [1014156094/vue-audio-player#17]
例如 mp3时长是 1:05:01  只会显示 05:01

原因是函数：
// 格式化秒为分
    formatTime: function formatTime(second) {
      return [parseInt(second / 60 % 60), parseInt(second % 60)].join(':').replace(/\b(\d)\b/g, '0$1');
    },

我项目是vue引用的的。找不到引用的文件。不知道怎么修改这个函数。

**Comment by 1014156094** [comment]
默认引用的文件在 node_modules/@liripeng/lib/vue-audio-player.umd.min.js

**Comment by 1014156094** [comment]
v1.0.8 已修复
