### ISSUE TITLE
不支持后台播放控制

### ISSUE THREAD

**Issue by liujianshe8899** [1014156094/vue-audio-player#21]
播放音乐时，当我切换到另一个页面，音乐被打断

**Comment by 1014156094** [comment]
项目用的是什么框架，单页面还是多页面

**Comment by liujianshe8899** [comment]
![image](https://user-images.githubusercontent.com/10411271/102029926-7a190100-3deb-11eb-8231-042994e359f1.png)

**Comment by liujianshe8899** [comment]
一个后台管理系统，多页面来回切换的

**Comment by 1014156094** [comment]
两种方法：
第一种：
页面主体内容使用 `<iframe/>` ，可以参考网易云（https://music.163.com/）观察它 DOM

第二种：
页面切换前存储当前播放时间，页面切换后加载之前存储的播放时间

**Comment by coderwang123** [comment]
为啥点播放事件的时候触发多次
![Uploading image.png…]()

**Comment by coderwang123** [comment]
为啥点播放事件的时候触发多次
![image](https://user-images.githubusercontent.com/59737619/105313002-c4ff1300-5bf8-11eb-9599-f074b0f8c0d2.png)

**Comment by 1014156094** [comment]
v1.2.4 版本已修复
