### ISSUE TITLE
关于PC端引入模拟Touch事件后的BUG

### ISSUE THREAD

**Issue by WhaleYolo** [1014156094/vue-audio-player#26]
PC端引入模拟Touch事件后，如果页面中存在input元素，点击input无法选中聚焦（可以通过nextTick获取元素后手动聚焦），且无法使用鼠标移动光标进行选中复制（未解决）

**Comment by WhaleYolo** [comment]
在吗在吗

**Comment by 1014156094** [comment]
在，是这库的问题 https://github.com/hammerjs/touchemulator/issues/2，我到时有空自己写下 PC 的拖拽吧

**Comment by WhaleYolo** [comment]
暂时没法解决是吗

**Comment by 1014156094** [comment]
暂时没法解决

**Comment by WhaleYolo** [comment]
好的，谢谢

**Comment by 1014156094** [comment]
v1.2.5 版本已经无需 touchemulator 即可在 PC 端拖拽
