### ISSUE TITLE
关于可拖拽点位置初始化是否有必要的问题

### ISSUE THREAD

**Issue by FreezingRiver** [1014156094/vue-audio-player#27]
播放时会初始化一次点的位置，具体偏移多少取决于点的```this.$refs.audioProgressPoint.offsetWidth```。
带来的后果就是，如果```this.$refs.audioProgressPoint```这个点稍微大了一点点，那么初始化的时候就会出现显著的向左偏移（尤其是移动端）

**Comment by 1014156094** [comment]
v1.2.6 版本已优化此问题，并且支持设置主题色
