### ISSUE TITLE
基于组件二次封装，通过refs调用play()等方法undefined

### ISSUE THREAD

**Issue by julylp** [1014156094/vue-audio-player#38]
在火狐浏览器中，this.$refs.mp3player.play() 会出现 t.$refs.audio.play(...) a undefined
谷歌浏览器无问题

**Comment by 1014156094** [comment]
代码截图看看，可能你代码有问题

**Comment by julylp** [comment]
火狐版本 52.0.2(64位)  
我尝试了未二次封装，按照你的示例播放器也无法加载。是浏览器版本太低么

**Comment by julylp** [comment]
![图片](https://user-images.githubusercontent.com/18521705/121451493-443a8b00-c9d0-11eb-9175-134b7c831696.png)
![图片](https://user-images.githubusercontent.com/18521705/121451520-53213d80-c9d0-11eb-8f4c-0c7719d13478.png)

**Comment by 1014156094** [comment]
我试了火狐 52.0 版本，版本太低了不行，现在最新的是 89 版本，更新就行了

**Comment by 1014156094** [comment]
我试了火狐 52.0 版本，这版本不行，现在最新的是 89 版本，你这远古版本太老了，升级下就行了
