### ISSUE TITLE
同时循环多个这个组件时  进度条有bug

### ISSUE THREAD

**Issue by yanningH16** [1014156094/vue-audio-player#4]
描述：进度条的bug
           
![image](https://user-images.githubusercontent.com/28645447/68370631-ea306e80-0177-11ea-8555-9795faedad13.png)

**Comment by 1014156094** [comment]
> 描述：进度条的bug
> 
> ![image](https://user-images.githubusercontent.com/28645447/68370631-ea306e80-0177-11ea-8555-9795faedad13.png)

哪个版本

**Comment by 1014156094** [comment]
我没复现出来，是哪个版本么？你提供下复现的 codeSandbox 链接吧，点击下面按钮 [![Edit @liripeng/vue-audio-player issue 模板](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/liripengvue-audio-player-issue-moban-cb57s?fontsize=14)

**Comment by tangwx820** [comment]
duration 在ios上显示NAN是怎么回事

**Comment by 1014156094** [comment]
> duration 在ios上显示NAN是怎么回事

我在 iOS 11.4.1 试了，没问题噢，你 iOS 版本多少？
