### ISSUE TITLE
请教：playing()方法没有实现，或者是如何调用的；

### ISSUE THREAD

**Issue by lancerAcher** [1014156094/vue-audio-player#40]
我要是实现的功能是类似于歌词滚动效果的，所以需要playing()播放中触发事件。我目前没有看懂作者你	playing()方法的调用方式

**Comment by 1014156094** [comment]
我有 `emit` 个 `playing` 事件，标签加上 @playing=""，文档有写

**Comment by lancerAcher** [comment]
解决了，谢谢您，我字父组件通信方法写错了。

**Comment by lancerAcher** [comment]
在单页面创建vue实例，如果通过引用组件的方法，如何实现？通过vue的组件		
components: {
			AudioPlayer:httpVueLoader('./@liripeng/vue-audio-player')
			},
发现路径不是很对，

**Comment by 1014156094** [comment]
是main.js里面，还是vue文件里面

**Comment by 1014156094** [comment]
![image](https://user-images.githubusercontent.com/16074662/125261652-0b296980-e334-11eb-8992-67058e8a3c7c.png)

**Comment by lancerAcher** [comment]
html 页面 单页面注册vue实例，无法进行组件注册。
`<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<script src="https://static.quhouse.com/zkgj/js/vue.min.js"></script>
	<link rel="stylesheet" href="./@liripeng/vue-audio-player/lib/vue-audio-player.css">
	<script src="https://unpkg.com/vue"></script> 
    <script src="https://unpkg.com/http-vue-loader"></script> 
	<title>Document</title>
</head>

<body>
	<div id="app">
		<audio-player
      ref="audioPlayer"
	  :show-prev-button='false'
	  :show-next-button='false'
      :audio-list="audioList.map(elm => elm.url)"
      :before-play="handleBeforePlay"
      theme-color="#ff2929"
	  @playing="playing"
    />
	</div>
</body>
<script>
	var app = new Vue({
		el: '#app',
		data() {
			return {
				audioList: [
		        {
		          name: '音频1',
		          url: 'https://static.quhouse.com/audio/d7879fbcdfcc436189ce79e643e0aeb8.mp3'
		        }
		      ]
			}
		},
		mounted() {},
		components: {
			AudioPlayer:httpVueLoader('./@liripeng/vue-audio-player')
			},
		methods: {
			handleBeforePlay(next) {
			console.log('我要开始播放了')
			
	        next() // 开始播放
			
	      },
		 playing(e){
		 	console.log("我播放中",this.$refs.audioPlayer.currentTime)
			
		 }
		}
	})
</script>

</html>`

**Comment by 1014156094** [comment]
没有npm吗

**Comment by 1014156094** [comment]
![image](https://user-images.githubusercontent.com/16074662/125272614-9f003300-e33e-11eb-96d4-145f06cebf78.png)
如果你没用npm的话，你下载这两个文件下来，引入到html里面应该就可以了，我现在不支持html方式引入，后面我可能加入这功能。

**Comment by 1014156094** [comment]
突然想起来可以这样，下载 `packages` 目录下来，引入 `index.js`
```
// 以下路径需根据项目实际情况填写
import VueAudioPlayer from '../../js/vue-audio-player/index.js'
```
