### ISSUE TITLE
npm i -S @liripeng/vue-audio-player 安装报错

### ISSUE THREAD

**Issue by zhengjunxiang** [1014156094/vue-audio-player#41]
安装报错：
![image](https://user-images.githubusercontent.com/21353414/128866761-7d5e22b4-9326-4aa3-a1d0-0575eedbe3fd.png)

**Comment by 1014156094** [comment]
我试了是可以的，npm国内比较慢，网络不快很容易安装失败，你多试几遍试试，或者你用淘宝的cnpm安装，或者你翻墙再试试
