### ISSUE TITLE
很赞，要是能够支持播放列表，选择歌曲播放就更好了！

### ISSUE THREAD

**Issue by lifa1225** [1014156094/vue-audio-player#43]
如题

**Comment by 1014156094** [comment]
暂时不支持播放列表，本库自由度比较高，你自己写二次开发下

**Comment by 1014156094** [comment]
暂时不支持播放列表，本库自由度比较高，你可以自己写二次开发下就有了

**Comment by dirkhe1051931999** [comment]
> 如题

for 循环便利不行就行了

for (var i = 0; i < index - this.$refs.audioPlayer.currentPlayIndex; i++) {
        this.$refs.audioPlayer.pause();
        setTimeout(() => {
          this.$refs.audioPlayer.playNext();
        });
      }

**Comment by 1014156094** [comment]
> > 如题
> 
> for 循环遍历不就行了 🐶🐶🐶🐶
> 
> for (var i = 0; i < index - this.$refs.audioPlayer.currentPlayIndex; i++) { this.$refs.audioPlayer.pause(); setTimeout(() => { this.$refs.audioPlayer.playNext(); }); }

楼主说的应该是要组件自带一个播放列表，哈哈哈
