### ISSUE TITLE
可以把源码放出来吗？我需要进度条在上面控制在下面的那种

### ISSUE THREAD

**Issue by checkwoodson** [1014156094/vue-audio-player#45]
我需要是把进度条放上面，控制放下面那种。无奈，你这个是打包好的，我也改不了里面的样式，以及修改新的功能。
希望作者可以修改一下

**Comment by checkwoodson** [comment]
不用了，我找到了。 抱歉 打扰各位了。
但是还是希望作者大大，可以配置进度条与控制的位置。
以及可以新增长按快进快退的功能。~谢谢~
这边我就人为改你的源码吧~。

**Comment by 1014156094** [comment]
嗯嗯，你想进度条放上面的话，你自己给进度条设置 margin-top 负数的值就能实现了，你说功能后面会考虑
