### ISSUE TITLE
苹果手机因为异步的问题导致加载完成后时长为0

### ISSUE THREAD

**Issue by checkwoodson** [1014156094/vue-audio-player#46]
ios或者vivo自带的浏览器 在初始化加载后，无法显示时长，
因为ios是异步的，而且他获取时长是播放后才能获取到时长。

**Comment by 1014156094** [comment]
你试试 loadedmetadata 事件触发后能不能获取到

**Comment by checkwoodson** [comment]
vivo和小米的自带浏览器是初始化不行的，点击播放才可以，你说的方法我早就试过了，我后来用durationchange解决oppo和苹果的问题，苹果的是飞书平台版本的原因好像，vivo的浏览器不确定，小米的也是如此。

**Comment by checkwoodson** [comment]
> 你试试 loadedmetadata 事件触发后能不能获取到，应该是可以的
作者可以试试增加durationchange事件来解决获取不到时长的问题，各个家的移动端自带的浏览器还是有点不一样。还有其他软件内置的浏览器，属实太恶心 了。
