### ISSUE TITLE
部分情况下，ios playing不触发

### ISSUE THREAD

**Issue by refrain1** [1014156094/vue-audio-player#47]
部分情况下，ios playing不触发
<audio-player id="audio" preload="auto" ref="audioPlayer" :audio-list="audioList.map((elm) => elm.url)"
				:playback-rates="[0.6,0.8,1.0,1.2,1.5]" :before-play="handleBeforePlay" theme-color="#FFFFFF"
				:before-next="reset_lyric" :isLoop="true" :disabled-progress-click="false"
				:disabled-progress-drag="false" :show-progress-bar="false" :playing="test()"
				:show-volume-button="false" :progressInterval="500" />

**Comment by 1014156094** [comment]
例如哪一个情况呢？

**Comment by refrain1** [comment]
抱歉，我自身项目bug导致的，没有注意到。。。
