### ISSUE TITLE
暂停状态下 点击下一首 歌曲已经切换 其它所有状态都没刷新  如进度条等

### ISSUE THREAD

**Issue by obliviondust** [1014156094/vue-audio-player#5]
你好，请使用下面的链接创建 issue 以帮助我们更快的排查问题。

https://codesandbox.io/s/liripengvue-audio-player-issue-moban-cb57s?fontsize=14

---

Please use the link below to create a new issue.

https://codesandbox.io/s/liripengvue-audio-player-issue-moban-cb57s?fontsize=14

**Comment by 1014156094** [comment]
v1.0.5 版本已修复
