### ISSUE TITLE
自动播放

### ISSUE THREAD

**Issue by vvvv110110** [1014156094/vue-audio-player#50]
无法自动播放

**Comment by liujiaxu1314** [comment]
自动播放怎么实现？

**Comment by 1014156094** [comment]
> 自动播放怎么实现？

![image](https://user-images.githubusercontent.com/16074662/190959655-8a26e384-20b7-4600-80d6-154284f81193.png)
这个示例就是自动播放的

**Comment by liujiaxu1314** [comment]
> > 自动播放怎么实现？
> 
> ![image](https://user-images.githubusercontent.com/16074662/190959655-8a26e384-20b7-4600-80d6-154284f81193.png) 这个示例就是自动播放的

这个事例进去播放不了呀

**Comment by 1014156094** [comment]
> > > 自动播放怎么实现？
> > 
> > 
> > ![image](https://user-images.githubusercontent.com/16074662/190959655-8a26e384-20b7-4600-80d6-154284f81193.png) 这个示例就是自动播放的
> 
> 这个事例进去播放不了呀

![image](https://user-images.githubusercontent.com/16074662/190978181-7e6be8dd-408a-4b2d-a23b-e053d55df415.png)
![image](https://user-images.githubusercontent.com/16074662/190978208-ba39f0eb-582e-400e-971e-49ef472377c3.png)
应该是你的 ip 被墙了

**Comment by liujiaxu1314** [comment]
麻烦问下 移动端这个播放器进度条无法拖拽 


| |
13718883621
|
|
***@***.***
|

**Comment by 1014156094** [comment]
> 麻烦问下 移动端这个播放器进度条无法拖拽 | | 13718883621 | | ***@***.*** | Message ID: ***@***.***>

苹果还是安卓，系统版本多少，用的是什么浏览器打开的？

**Comment by liujiaxu1314** [comment]
拖拽那个是我自己修改导致的  但是 iOS手机上  总时长显示不出来。
| |
13718883621
|
|
***@***.***
|
签名由网易邮箱大师定制


在2022年10月27日 11:17，Li Ri ***@***.***> 写道：

麻烦问下 移动端这个播放器进度条无法拖拽 | | 13718883621 | | @.*** | Message ID: @.***>

苹果还是安卓，系统版本多少，用的是什么浏览器打开的？

**Comment by 1014156094** [comment]
> 

时间格式 xxxx-xx-xx 在 iOS 是不兼容的，需要 xxxx/xx/xx，你看看你是不是动了时间的代码

**Comment by liujiaxu1314** [comment]
// 当媒介元素的持续时间以及其它媒介已加载数据时运行脚本
onLoadedmetadata(event) {
this.duration=this.$refs.audio.duration
this.$emit('loadedmetadata', event)
},
iOS手机 他不会走进去这个方法 导致总时长获取不到 😂




| |
13718883621
|
|
***@***.***
|
签名由网易邮箱大师定制


在2022年10月27日 11:37，Li Ri ***@***.***> 写道：

时间格式 xxxx-xx-xx 在 iOS 是不兼容的，需要 xxxx/xx/xx，你看看你是不是动了时间的代码

**Comment by 1014156094** [comment]
> 

iOS我试过没问题的，你iOS多少的版本

**Comment by liujiaxu1314** [comment]
iOS 15.4    在微信里打开的 （本地调试） 
| |
13718883621
|
|
***@***.***
|
签名由网易邮箱大师定制


在2022年10月27日 14:14，Li Ri ***@***.***> 写道：

iOS我试过没问题的，你iOS多少的版本

**Comment by 1014156094** [comment]
不是我组件的问题，浏览器的问题，大部分浏览器会禁用自动播放音频的（特别是手机端），详情可看这 [https://developer.mozilla.org/zh-CN/docs/Web/Media/Autoplay_guide](https://github.com/1014156094/vue-audio-player/issues/url)
