### ISSUE TITLE
问题求解

### ISSUE THREAD

**Issue by Dreamingcx** [1014156094/vue-audio-player#51]
![图片](https://user-images.githubusercontent.com/52815450/169979258-13ff78d9-50ff-4175-a814-81f462102bc4.png)
单击控制按钮（播放、暂停、上一首、下一首）控制台出现 Uncaught ReferenceError: s is not defined

**Comment by 1014156094** [comment]
音乐地址发一下

**Comment by Dreamingcx** [comment]
http://txh-cdn.96qbhy.com/20180817175211dtC1vE3z.mp3,我用了示例里面的音乐地址，出现了这个问题，换了其他音频地址之后还是出现了这个问题

**Comment by 1014156094** [comment]
> [http://txh-cdn.96qbhy.com/20180817175211dtC1vE3z.mp3,我用了示例里面的音乐地址，出现了这个问题，换了其他音频地址之后还是出现了这个问题](http://txh-cdn.96qbhy.com/20180817175211dtC1vE3z.mp3,%E6%88%91%E7%94%A8%E4%BA%86%E7%A4%BA%E4%BE%8B%E9%87%8C%E9%9D%A2%E7%9A%84%E9%9F%B3%E4%B9%90%E5%9C%B0%E5%9D%80%EF%BC%8C%E5%87%BA%E7%8E%B0%E4%BA%86%E8%BF%99%E4%B8%AA%E9%97%AE%E9%A2%98%EF%BC%8C%E6%8D%A2%E4%BA%86%E5%85%B6%E4%BB%96%E9%9F%B3%E9%A2%91%E5%9C%B0%E5%9D%80%E4%B9%8B%E5%90%8E%E8%BF%98%E6%98%AF%E5%87%BA%E7%8E%B0%E4%BA%86%E8%BF%99%E4%B8%AA%E9%97%AE%E9%A2%98)

http://txh-cdn.96qbhy.com/20180817175211dtC1vE3z.mp3 你这个MP3链接坏的，而且播放器已经提示出来了
