### ISSUE TITLE
怎么使用插槽更改样式

### ISSUE THREAD

**Issue by chenzihao0731** [1014156094/vue-audio-player#53]

**Comment by 1014156094** [comment]
![image](https://user-images.githubusercontent.com/16074662/176154489-f35ca6c6-bc0a-48d2-8413-1c7039e03182.png)
有这些插槽可以使用，如果要改进度条的样式，可以直接覆盖样式，vue style 加了 scoped 的话覆盖样式要使用 :deep() 深度选择器

**Comment by chenzihao0731** [comment]
您好，我引入这个插件发现点击播放或者暂停音频的时候会出现一个这样的错误
Uncaught ReferenceError: s is not defined 能帮忙看下吗

**Comment by 1014156094** [comment]
> 您好，我引入这个插件发现点击播放或者暂停音频的时候会出现一个这样的错误 Uncaught ReferenceError: s is not defined 能帮忙看下吗

发代码出来或提供 demo 才能帮到你
