### ISSUE TITLE
Cannot read properties of null (reading 'duration')

### ISSUE THREAD

**Issue by MichalKrakow** [1014156094/vue-audio-player#54]
```// 当媒介元素的持续时间以及其它媒介已加载数据时运行脚本
    onLoadedmetadata(event) {
      this.duration = this.$refs.audio.duration
      this.$emit('loadedmetadata', event)
 },
```
This event fires even after the player has been removed. This happens when view holding player gets unmounted, before the player loads media.

Is there some destroy method to be called upon unmount?

**Comment by 1014156094** [comment]
![image](https://github.com/1014156094/vue-audio-player/assets/16074662/57377747-65b3-48db-9a9a-9b82b646243b)
The page is closed will automatically destroy, I did not reproduce your BUG, you update the version to see?
