### ISSUE TITLE
如何播放列表中指定歌曲

### ISSUE THREAD

**Issue by Jcanno** [1014156094/vue-audio-player#55]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by 1014156094** [comment]
这样子，我加了个示例
![image](https://user-images.githubusercontent.com/16074662/194736030-74d2b2eb-f7d5-4121-b289-1c54385a5d30.png)
![image](https://user-images.githubusercontent.com/16074662/194736023-852bb4ef-7a78-45e2-b15b-f8d03c983bb0.png)
