### ISSUE TITLE
拖拽进度条后，会出现多个声音叠加

### ISSUE THREAD

**Issue by sparGuan** [1014156094/vue-audio-player#57]
![image](https://user-images.githubusercontent.com/28480563/221796849-5948a414-ed7c-4e9d-9d1c-d7780d89e467.png)
这段代码写的有问题，每次拖拽的时候触发play就会生成一个新的定时器，然后又产出一个声音

**Comment by 1014156094** [comment]
应该不是这个问题，新的定时器之前是有清除的，你是什么浏览器

**Comment by sparGuan** [comment]
你直接把时间
![image](https://user-images.githubusercontent.com/28480563/228119712-6c26bad8-72dd-46e2-97f0-be3d70543aff.png)
this.currentTime = this.$refs.audio.currentTime
直接设置进去，是完全不需要再去去初始化的，你一直重复初始化会一直产生新的播放的声音

**Comment by 1014156094** [comment]
> 你直接把时间 ![image](https://user-images.githubusercontent.com/28480563/228119712-6c26bad8-72dd-46e2-97f0-be3d70543aff.png) this.currentTime = this.$refs.audio.currentTime 直接设置进去，是完全不需要再去去初始化的，你一直重复初始化会一直产生新的播放的声音

没听出来有新的播放声音，但你说的这个是可以优化的点

**Comment by 1014156094** [comment]
v1.5.1 已更新
