### ISSUE TITLE
Changing currentTime turns back to original position.

### ISSUE THREAD

**Issue by ZoranPrascevic** [1014156094/vue-audio-player#58]
I just want to change the currentTime value +-10 seconds using button click, I control the player through ref. But it returns back to the original position immediately. I just use this way, this.audioPlayer.currentTime += 10
All other methods work without any issue.

**Comment by ZoranPrascevic** [comment]
So it turns into this simple question.
How can I change the data values? (currentTime and playbackRate)

**Comment by 1014156094** [comment]
![image](https://github.com/1014156094/vue-audio-player/assets/16074662/7c45e272-1a08-4dce-85ca-61f45f04fff5)
