### ISSUE TITLE
Could you please share an example how to use the "ended"-event?

### ISSUE THREAD

**Issue by ManiMatter** [1014156094/vue-audio-player#68]
Hi,

I've been trying to make use of the events, particularly the "ended" event.
I want to trigger a function (super simple example below) once the player has reached the end, but I cant figure out how to do it.

It would be great if you could share an example, potentially in the docs

```
    function triggerOnEnd() {
      console.log('Has ended')
    }
```

**Comment by 1014156094** [comment]
![image](https://github.com/1014156094/vue-audio-player/assets/16074662/5e12deca-6b3e-4532-953f-aaa80348a536)

**Comment by ManiMatter** [comment]
Hi @1014156094 

I have seen the „ended“ event in the readme, but I have no clue how to use it.

i tried many approaches but could not figure it out, hence my ask if you could share an example how these events can be used?

**Comment by 1014156094** [comment]
![image](https://github.com/1014156094/vue-audio-player/assets/16074662/d7e2de09-faa7-4d5f-91dc-7da7a530cb8a)

**Comment by ManiMatter** [comment]
Thank you!
