### ISSUE TITLE
Next song does not automatically play on iPhone when screen is locked 

### ISSUE THREAD

**Issue by ManiMatter** [1014156094/vue-audio-player#69]
When screen of iPhone is locked, the next song does not play.

This solution here has figured out somehow how the next track can be played: https://github.com/Tresre/music

Demo: https://tresre.dev/music/

Any chance this could be brought to your player too?

What I also really like is that it brings the "previous" and "next" buttons onto the mini-player of iOS on the locked screen.

**Comment by 1014156094** [comment]
v1.6.0 Supported 
https://codesandbox.io/p/sandbox/immutable-browser-cb57s?file=%2Fsrc%2FApp.vue%3A30%2C19&resolutionHeight=675&resolutionWidth=320

**Comment by ManiMatter** [comment]
Fantastic. On the demo link, I get:

**Sandbox not found**

It's likely that the Sandbox you're trying to access doesn't exist or you don't have the required permissions to access it.
If the issue persists, please contact our support team at [support@codesandbox.io](mailto:support@codesandbox.io) for further assistance, making sure to copy the error details below.

**Comment by 1014156094** [comment]
> Fantastic. On the demo link, I get:
> 
> **Sandbox not found**
> 
> It's likely that the Sandbox you're trying to access doesn't exist or you don't have the required permissions to access it. If the issue persists, please contact our support team at [support@codesandbox.io](mailto:support@codesandbox.io) for further assistance, making sure to copy the error details below.

![image](https://github.com/1014156094/vue-audio-player/assets/16074662/db144c6d-1313-4be3-a893-1e937457b9b3)

**Comment by ManiMatter** [comment]
using the link in the readme to online demo i get from iphone:

> Not Found
> We could not find the sandbox you're looking for.
> If the sandbox is private, you might need to [sign in](https://codesandbox.io/signin)
> and reload ethe page to see the sandbox.

**Comment by 1014156094** [comment]
![image](https://github.com/1014156094/vue-audio-player/assets/16074662/8c0ec03c-3315-4563-8926-c8d4960a1641)
There are also examples here

**Comment by ManiMatter** [comment]
Thx will def try to get it to work for me.

 Hope the demo comes back though, it's great to see the working example and follow it. 

Thanks again for your work on this

**Comment by 1014156094** [comment]
The previous version has a bug lock screen does not work, you can update to v1.6.2
