### ISSUE TITLE
进度条时间有点小问题

### ISSUE THREAD

**Issue by Yvonne-Tan** [1014156094/vue-audio-player#73]
请打开下面的链接后点击右上角 fork，然后放您的代码上去复现问题，最后将链接发出来，以便作者排查，谢谢。（Please open the link below and click on the top right corner fork, then put your code to duplicate the problem, and finally post the link for the author to check, thank you.）

https://codesandbox.io/s/liripengvue-audio-player-issue-moban-cb57s?file=/src/App.vue&resolutionWidth=320&resolutionHeight=675
您好，在使用您的组件过程中，发现进度条出现0:60的情况，应该显示为1：00，想烦请您解决，谢谢~

**Comment by 1014156094** [comment]
谢谢反馈，v2.0.3版本已修复
